### ISSUE TITLE
requireLicenseAcceptance option seems not working

### ISSUE THREAD

**Issue by Landry25** [electron-userland/electron-installer-windows#246]
**What version of `electron-installer-windows` are you using?**
1.1.0
**What version of `node` and `npm` are you using?**
npm 6.1.0
node v8.11.2
**What operating system are you using?**
windows7
**Can you compile the [example app](https://github.com/electron-userland/electron-installer-windows/tree/master/example) successfully?**
yes
**What did you do? Please include the configuration you are using for `electron-installer-windows`.**
I succeed to generate an installer for my app without option.
Now I'm trying to add a requireLicenseAcceptance .
For test purpose i tried : 
electron-installer-windows --src build/myapp-win32-x64/ --dest dist/ --licenseUrl https://github.com/squirrel/Squirrel.Windows/blob/master/COPYING  --requireLicenseAcceptance true
the installer is generated but..

**What did you expect to happen?**
i was expecting a prompt during launch of installer saying "please accept the license"
**What actually happened?**
the installer working well but without asking for license agreement.

**Comment by fcastilloec** [comment]
The `--licenseUrl` and `--requireLicenseAcceptance` options are not valid command-line arguments, use `--options.licenseUrl` and `--options.requireLicenseAcceptance` as stated in the READM. It's always better to create a `.json` configuration file and pass that with the option `--config`.
Once you've done that, test it and it should work now. If it doesn't, please copy/paste the output of running your command with `DEBUG=electron-installer-windows`

**Comment by Landry25** [comment]
Thanks for your answer.
I tried with the following config.json file : 
{
  "dest": "dist/",
  "src": "build/myapp-win32-x64/",
  "options": {
    "licenseUrl": "https://github.com/squirrel/Squirrel.Windows/blob/master/COPYING",
    "requireLicenseAcceptance": true
  }
}
without success.
Here is the log : 
C:\Data\Visual_Studio_Code_Projects\Nodered-installer>electron-installer-windows --config config.json
Creating package (this may take a while)
  electron-installer-windows Reading package metadata from build\myapp-win32-x64\resources\app\package.json +0ms
  electron-installer-windows Creating package with options
  electron-installer-windows {
  electron-installer-windows   "help": false,
  electron-installer-windows   "config": "config.json",
  electron-installer-windows   "dest": "dist/",
  electron-installer-windows   "src": "build/myapp-win32-x64/",
  electron-installer-windows   "options": {
  electron-installer-windows     "licenseUrl": "https://github.com/squirrel/Squirrel.Windows/blob/master/COPYING",
  electron-installer-windows     "requireLicenseAcceptance": true
  electron-installer-windows   },
  electron-installer-windows   "licenseUrl": "https://github.com/squirrel/Squirrel.Windows/blob/master/COPYING",
  electron-installer-windows   "requireLicenseAcceptance": true,
  electron-installer-windows   "name": "myapp",
  electron-installer-windows   "productName": "myapp",
  electron-installer-windows   "description": "myapp",
  electron-installer-windows   "productDescription": "myapp",
  electron-installer-windows   "version": "0.0.1",
  electron-installer-windows   "copyright": "Copyright © 2019 LDE",
  electron-installer-windows   "authors": [
  electron-installer-windows     "LDE"
  electron-installer-windows   ],
  electron-installer-windows   "owners": [
  electron-installer-windows     "LDE"
  electron-installer-windows   ],
  electron-installer-windows   "exe": "myapp.exe",
  electron-installer-windows   "icon": "C:\\Users\\LDE\\AppData\\Roaming\\npm\\node_modules\\electron-installer-windows\\resources\\icon.ico",
  electron-installer-windows   "animation": "C:\\Users\\LDE\\AppData\\Roaming\\npm\\node_modules\\electron-installer-windows\\resources\\animation.gif",
  electron-installer-windows   "tags": [],
  electron-installer-windows   "noMsi": false
  electron-installer-windows } +16ms
  electron-installer-windows Creating temporary directory +0ms
  electron-installer-windows Creating subdirectories under C:\Users\LDE\AppData\Local\Temp\electron-11384biw6UPEKZMEh\myapp_0.0.1 +15ms
  electron-installer-windows Creating contents of package +0ms
  electron-installer-windows Creating spec file at C:\Users\LDE\AppData\Local\Temp\electron-11384biw6UPEKZMEh\myapp_0.0.1\nuget\myapp.nuspec +0ms
  electron-installer-windows Generating template from C:\Users\LDE\AppData\Roaming\npm\node_modules\electron-installer-windows\resources\spec.ejs +0ms
  electron-installer-windows Copying application to C:\Users\LDE\AppData\Local\Temp\electron-11384biw6UPEKZMEh\myapp_0.0.1\myapp+0ms
  electron-installer-windows Generated template from C:\Users\LDE\AppData\Roaming\npm\node_modules\electron-installer-windows\resources\spec.ejs
  electron-installer-windows <?xml version="1.0" encoding="utf-8"?>
  electron-installer-windows <package xmlns="http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd">
  electron-installer-windows   <metadata>
  electron-installer-windows     <id>myapp</id>
  electron-installer-windows     <title>myapp</title>
  electron-installer-windows     <summary>myapp</summary>
  electron-installer-windows     <description>myapp</description>
  electron-installer-windows     <version>0.0.1</version>
  electron-installer-windows     <copyright>Copyright © 2019 LDE</copyright>
  electron-installer-windows     <authors>LDE</authors>
  electron-installer-windows     <owners>LDE</owners>
  electron-installer-windows
  electron-installer-windows
  electron-installer-windows     <licenseUrl>https://github.com/squirrel/Squirrel.Windows/blob/master/COPYING</licenseUrl>
  electron-installer-windows     <requireLicenseAcceptance>true</requireLicenseAcceptance>
  electron-installer-windows
  electron-installer-windows   </metadata>
  electron-installer-windows   <files>
  electron-installer-windows     <file src="locales\**" target="lib\net45\locales" />
  electron-installer-windows     <file src="resources\**" target="lib\net45\resources" />
  electron-installer-windows     <file src="*.bin" target="lib\net45" />
  electron-installer-windows     <file src="*.dll" target="lib\net45" />
  electron-installer-windows     <file src="*.pak" target="lib\net45" />
  electron-installer-windows     <file src="Update.exe" target="lib\net45\squirrel.exe" />
  electron-installer-windows     <file src="icudtl.dat" target="lib\net45\icudtl.dat" />
  electron-installer-windows     <file src="LICENSE" target="lib\net45\LICENSE" />
  electron-installer-windows     <file src="myapp.exe" target="lib\net45\myapp.exe" />
  electron-installer-windows   </files>
  electron-installer-windows </package>
  electron-installer-windows  +0ms
  electron-installer-windows Creating package at C:\Users\LDE\AppData\Local\Temp\electron-11384biw6UPEKZMEh\myapp_0.0.1 +20s
  electron-installer-windows Executing command: C:\Users\LDE\AppData\Roaming\npm\node_modules\electron-installer-windows\vendor\nuget\NuGet.exe pack C:\Users\LDE\AppData\Local\Temp\electron-11384biw6UPEKZMEh\myapp_0.0.1\nuget\myapp.nuspec -BasePath C:\Users\LDE\AppData\Local\Temp\electron-11384biw6UPEKZMEh\myapp_0.0.1\myapp -OutputDirectory C:\Users\LDE\AppData\Local\Temp\electron-11384biw6UPEKZMEh\myapp_0.0.1\nuget -NoDefaultExcludes +0ms
  electron-installer-windows Finding package with pattern C:\Users\LDE\AppData\Local\Temp\electron-11384biw6UPEKZMEh\myapp_0.0.1\nuget\*.nupkg +25s
  electron-installer-windows Releasifying package at C:\Users\LDE\AppData\Local\Temp\electron-11384biw6UPEKZMEh\myapp_0.0.1 +0ms
  electron-installer-windows Executing command: C:\Users\LDE\AppData\Roaming\npm\node_modules\electron-installer-windows\vendor\squirrel\Squirrel.com --releasify C:/Users/LDE/AppData/Local/Temp/electron-11384biw6UPEKZMEh/myapp_0.0.1/nuget/myapp.0.0.1.nupkg --releaseDir C:\Users\LDE\AppData\Local\Temp\electron-11384biw6UPEKZMEh\myapp_0.0.1\squirrel --setupIcon C:\Users\LDE\AppData\Roaming\npm\node_modules\electron-installer-windows\resources\icon.ico --loadingGif
C:\Users\LDE\AppData\Roaming\npm\node_modules\electron-installer-windows\resources\animation.gif +0ms
  electron-installer-windows Moving package to destination +3m
  electron-installer-windows Moving file C:/Users/LDE/AppData/Local/Temp/electron-11384biw6UPEKZMEh/myapp_0.0.1/squirrel/RELEASES to dist\RELEASES +16ms
  electron-installer-windows Moving file C:/Users/LDE/AppData/Local/Temp/electron-11384biw6UPEKZMEh/myapp_0.0.1/squirrel/Setup.exe to dist\myapp-0.0.1-setup.exe +0ms
  electron-installer-windows Moving file C:/Users/LDE/AppData/Local/Temp/electron-11384biw6UPEKZMEh/myapp_0.0.1/squirrel/Setup.msi to dist\myapp-0.0.1-setup.msi +0ms
  electron-installer-windows Moving file C:/Users/LDE/AppData/Local/Temp/electron-11384biw6UPEKZMEh/myapp_0.0.1/squirrel/myapp-0.0.1-full.nupkg to dist\myapp-0.0.1-full.nupkg +0ms
  electron-installer-windows Successfully created package at dist/ +54ms
Successfully created package at dist/

**Comment by Landry25** [comment]
thank you @fcastilloec . Implementing the license agreement directly in the app is my back up solution, even it will come too late for me because the installation is done and then when you launch the application you have a request of license validation.

**Comment by fcastilloec** [comment]
@Landry25 as a last result, you could use [electron-wix-msi](https://github.com/felixrieseberg/electron-wix-msi). You might be able to create your own template, and mention the license, and provide a link to it, and by clicking `NEXT` they agree with it. I'm not familiar with this module, but it might have some potential.

**Comment by Landry25** [comment]
@fcastilloec Thank you for the proposal. I tried it yesterday but no success, seems quite complex to put in place with additonal SW download and result of installation is not what i expected ( in program files plenty of files copied ).

**Comment by fcastilloec** [comment]
@Landry25 I've confirm with the developes of Windows.Squirrel, which is what we used to create the installer, that both `licenseUrl` and `requireLicenseAcceptance` don't to anything on the final `.exe`, but they might still have a role on the `.nupkg`.
The recommendation on how to deal with this scenario is (and a quote from the developers of Windows.Squirrel):
> Squirrel installers show no UI, if you want your users to accept a EULA, do it the first time your app starts

So, you'll have to create an UI inside your app for the license, and you can use the squirrel event `--squirrel-firstrun`, heres more on it: [Custom Squirrel Events](https://github.com/Squirrel/Squirrel.Windows/blob/master/docs/using/custom-squirrel-events-non-cs.md#application-startup-commands).
To check for that event, or any event, just check that `process.argv[1] ` equals any of the events you need. Here's an [example code](https://github.com/electron/windows-installer#handling-squirrel-events) from another project.

We're in the process of deciding what to do regarding these options.

**Comment by Landry25** [comment]
You can find potential solutions here :  
- electron-wix-msi  with patch provided by ThierryLeGal
- innosetup
