### ISSUE TITLE
Cannot read property \'url\' of undefined\n    at readMeta.then.pkg

### ISSUE THREAD

**Issue by axfelix** [electron-userland/electron-installer-windows#252]
**What version of `electron-installer-windows` are you using?**
Most recent

**What version of `node` and `npm` are you using?**
6.5.0

**What operating system are you using?**
Windows 10

**Can you compile the [example app](https://github.com/electron-userland/electron-installer-windows/tree/master/example) successfully?**
Yes

**What did you do? Please include the configuration you are using for `electron-installer-windows`.**
`$ electron-installer-windows --src radiam-agent-win32-x64/ --dest ~/Desktop/`

**What did you expect to happen?**
Package to get built

**What actually happened?**
```
Creating package (this may take a while)
TypeError: Cannot read property 'url' of undefined
    at readMeta.then.pkg (C:\Users\axfel\AppData\Roaming\npm\node_modules\electron-installer-windows\src\installer.js:71:22)
    at <anonymous> 'TypeError: Cannot read property \'url\' of undefined\n    at readMeta.then.pkg (C:\\Users\\axfel\\AppData\\Roaming\\npm\\node_modules\\electron-installer-windows\\src\\installer.js:71:22)\n    at <anonymous>'
```

**Comment by fcastilloec** [comment]
There's an error on your `package.json` and not with this module. Very likely you're missing `homepage` or `author.url` in your `package.json`. If you share your `package.json` we can tell you exactly what's going on, or just run your project with `DEBUG=electron-installer-windows` before your command and post the output here.

**Comment by axfelix** [comment]
Yup, thanks!

**Comment by axfelix** [comment]
Actually, I'm still hitting this after verifying my package.json should be good...

```
{
  "name": "radiam-agent",
  "version": "0.0.1",
  "homepage": "https://git.computecanada.ca/radiam/radiam-agent",
  "main": "main.js",
  "scripts": {
    "start": "electron ."
  },
  "devDependencies": {
    "electron": "2.0.17",
    "node-notifier": "^5.4.0",
    "portfinder": "^1.0.20",
    "zerorpc": "^0.9.8"
  },
  "dependencies": {
    "node-notifier": "^5.4.0",
    "zerorpc": "^0.9.8"
  },
  "files": [
    "dist/radiam_tray.exe",
    "dist/radiam_tray"
  ],
  "author": {
    "name": "Yang Zhou",
    "email": "yang_zhou_6@sfu.ca",
    "url": "http://computecanada.ca"
  }
}
```

How should I run that debug command exactly?

**Comment by fcastilloec** [comment]
It's very likely that the error that you're getting now it's not the URL error, checking your `name` field, this is related to #249

**Comment by axfelix** [comment]
Good guess, but I've removed those, and I think I'm still hitting the issue...

Also, sorry, I'm running under bash but I don't understand the syntax of the `DEBUG=electron-installer-windows` command you're suggesting. Can I see complete syntax for that debug command?

**Comment by fcastilloec** [comment]
Assuming the command you use is the first one in this issue report, you need to run:
`DEBUG=electron-installer-windows electron-installer-windows --src radiam-agent-win32-x64/ --dest ~/Desktop/`
Just prepend the debug command to whatever command you use to run this module, even if it's an npm script.

**Comment by axfelix** [comment]
Thanks! Not too much more enlightening here:

```
$ DEBUG=electron-installer-windows electron-installer-windows --src radiamagent-win32-x64/ --dest ~/Desktop/
Creating package (this may take a while)
  electron-installer-windows Reading package metadata from radiamagent-win32-x64\resources\app\package.json +0ms
  electron-installer-windows Error creating package: expected author to be a string +4ms
TypeError: expected author to be a string
    at module.exports (C:\Users\axfel\AppData\Roaming\npm\node_modules\electron-installer-windows\node_modules\parse-author\index.js:14:11)
    at common.readMetadata.then.pkg (C:\Users\axfel\AppData\Roaming\npm\node_modules\electron-installer-windows\src\installer.js:121:26)
    at <anonymous> 'TypeError: expected author to be a string\n    at module.exports (C:\\Users\\axfel\\AppData\\Roaming\\npm\\node_modules\\electron-installer-windows\\node_modules\\parse-author\\index.js:14:11)\n    at common.readMetadata.then.pkg (C:\\Users\\axfel\\AppData\\Roaming\\npm\\node_modules\\electron-installer-windows\\src\\installer.js:121:26)\n    at <anonymous>'
```

**Comment by fcastilloec** [comment]
You're right, there's a bug with this module that was introduced when we switch to the new `electron-installer-common`. We'll release a fix soon.
As a workaround set your author filed as a single string (see https://docs.npmjs.com/files/package.json#people-fields-author-contributors)

**Comment by axfelix** [comment]
Success! Thanks! But I wasn't even able to list multiple authors this way, so I do think this needs fixing.

**Comment by fcastilloec** [comment]
If you want to set multiple authors, then you have to use this module `option.authors` and specify an array with all the authors names. As mentioned in the [README](https://github.com/electron-userland/electron-installer-windows#optionsauthors), the default is `package.author` which is a single person.
