### ISSUE TITLE
App is launched during install process

### ISSUE THREAD

**Issue by axfelix** [electron-userland/electron-installer-windows#257]
**What version of `electron-installer-windows` are you using?**
1.1.1

**What version of `node` and `npm` are you using?**
6.5.0

**What operating system are you using?**
Windows 10

**Can you compile the [example app](https://github.com/electron-userland/electron-installer-windows/tree/master/example) successfully?**
Yes

**What did you do? Please include the configuration you are using for `electron-installer-windows`.**
`electron-installer-windows --src radiamagent-win32-x64/ --dest ~/Desktop --config config.json`

**What did you expect to happen?**
App to be installed and shortcuts created

**What actually happened?**
App is launched during install process (seemingly multiple times, as there are a few "ghost" tray icons that disappear on mouseover) and no shortcuts are created.

I know I've been opening several issues lately but I've been reviewing the docs and I don't understand why this should be happening... the installer shouldn't launch the app, right?

**Comment by fcastilloec** [comment]
Given that this module only automates the creation of an installer using Squirrel, it's the user's responsibility to deal with shortcuts, tray icons, and other app-related issues.
I think you're probably not handling any of the Squirrel events, given that that's what we use. That is well documented on the Squirrel page (https://github.com/Squirrel/Squirrel.Windows/blob/master/docs/using/custom-squirrel-events-non-cs.md)

You should use [`electron-squirrel-startup`](https://github.com/Squirrel/Squirrel.Windows/blob/master/docs/using/custom-squirrel-events-non-cs.md) to deal with all events, which include desktop shortcut creation. They have a `Read More` section which can helpt you with more details.

**Comment by axfelix** [comment]
OK, thanks -- I'm just not clear on why it's not behaving like the example app, because as far as I can tell I've followed all of the buildscript-specific stuff to the letter.
