### ISSUE TITLE
error creating package 'TypeError: expected author to be a string'

### ISSUE THREAD

**Issue by lakhank143** [electron-userland/electron-installer-windows#267]
Hello,
I have developed an app in angular 6. now I want to make desktop application of it. I have installed electron, electron packager & electron-installer-windows globally. I have tested my build in development it's working fine. I have created a build using windows packager. now I am creating a Windows package but when I run my command it shows me some error like 'TypeError: expected author to be a string'. I don't even understand what is the problem. where Linux build is successfully created. 

following are some steps I am performing. 

1. npm run electron-build
2. electron-packager . --platform=win32 --arch=all
3. electron-installer-windows --src task-reporting-tool-win32-x64 --dest ../task-reporting-tool

package.json
`
{
  "name": "task-reporting-tool",
  "version": "0.0.0",
  "description": "TRTool",
  "main": "main.js",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "electron": "electron .",
    "electron-build": "ng build --prod && electron ."
  },
  "private": true,
  "author": {
    "name": "Lakhan",
    "email": "lakhank2951@gmail.com",
    "url": "http://mohartech.com"
  }
}
`

in my package.json file, I have mentioned description, author, etc. so why it is throwing an error of  'TypeError: expected author to be a string'?

![collage](https://user-images.githubusercontent.com/30143510/55626723-e72c6480-57c9-11e9-80ac-aa16283a7e00.jpg)

**Comment by fcastilloec** [comment]
This has already been solved but we haven't released a new version yet. See https://github.com/electron-userland/electron-installer-windows/issues/252#issuecomment-467229159
As stated there, a workaround is to change your `package.json` author to be a single string rather than an object. Or you can directly pass the author in `options.authors` in your config file.

**Comment by lakhank143** [comment]
I have tried using a single string author. still, it is throwing me the same error & where is the "options.authors" config file.

**Comment by lakhank143** [comment]
now I have created a config.json file as follows.
`{
    "author":"Lakhan"
}`

trying to make a build using the following command

electron-installer-windows --src task-reporting-tool-win32-x64 --dest ../task-reporting-tool --config config.json
but now there is another error  'Could not load type 'System.AppContext' from assembly' 
![Screenshot from 2019-04-08 12-25-03](https://user-images.githubusercontent.com/30143510/55704500-dfeb9d80-59f9-11e9-98de-761793968365.png)
the above screenshot displays the error

**Comment by fcastilloec** [comment]
Please read the README to see how to use the options. The name of the option and the type are all wrong. It's `options` (plural) and you need to pass an array.

https://github.com/electron-userland/electron-installer-windows#optionsauthors

**Comment by hygkui** [comment]
Thanks! @fcastilloec 
it helps me understand what happens
