### ISSUE TITLE
Installer isnt working on windows 32 bit

### ISSUE THREAD

**Issue by skopz356** [electron-userland/electron-installer-windows#295]
I am using version 2.0.0 of electron-installer-windows on ubuntu 16.04 with node 10 and npm 
6.9.
I builded my app using electron-packager for win32.

I have compiled my app without any problem, the installer works fine on Windows 64 but when I run it on Windows 32bit I get error:
2019-11-11 16:41:29> Program: Starting Squirrel Updater: --install .
2019-11-11 16:41:30> Program: Starting install, writing to C:\Users\tomas\AppData\Local\SquirrelTemp
2019-11-11 16:41:31> Program: About to install to: C:\Users\tomas\AppData\Local\electron_pdf
2019-11-11 16:41:32> CheckForUpdateImpl: Couldn't write out staging user ID, this user probably shouldn't get beta anything: System.IO.DirectoryNotFoundException: Část cesty C:\Users\tomas\AppData\Local\electron_pdf\packages\.betaId nebyla nalezena.
   v System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   v System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   v System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   v System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   v System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   v System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   v System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
   v Squirrel.UpdateManager.CheckForUpdateImpl.getOrCreateStagedUserId()
2019-11-11 16:41:32> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Část cesty C:\Users\tomas\AppData\Local\electron_pdf\packages\RELEASES nebyla nalezena.
   v System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   v System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   v System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   v Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   v Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
2019-11-11 16:41:32> CheckForUpdateImpl: Reading RELEASES file from C:\Users\tomas\AppData\Local\SquirrelTemp
2019-11-11 16:41:32> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2019-11-11 16:41:33> ApplyReleasesImpl: Writing files to app directory: C:\Users\tomas\AppData\Local\electron_pdf\app-0.0.1
2019-11-11 16:41:46> LogHost: Rigging execution stub for electron_pdf_ExecutionStub.exe to C:\Users\tomas\AppData\Local\electron_pdf\electron_pdf.exe
2019-11-11 16:41:54> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\tomas\AppData\Local\electron_pdf\app-0.0.1\electron_pdf.exe]
2019-11-11 16:41:55> ApplyReleasesImpl: Couldn't run Squirrel hook, continuing: C:\Users\tomas\AppData\Local\electron_pdf\app-0.0.1\electron_pdf.exe: System.ComponentModel.Win32Exception (0x80004005): Zadaný spustitelný soubor není platnou aplikací pro tuto platformu OS.
   v System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   v System.Diagnostics.Process.Start()
   v System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   v Squirrel.Utility.<InvokeProcessAsync>d__11.MoveNext()
--- Konec trasování zásobníku z předchozího místa, ze kterého byla vyvolána výjimka ---
   v System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   v System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   v Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass10_0.<<invokePostInstall>b__0>d.MoveNext()
2019-11-11 16:41:55> IEnableLogger: Failed to invoke post-install: System.ComponentModel.Win32Exception (0x80004005): Zadaný spustitelný soubor není platnou aplikací pro tuto platformu OS.
   v System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   v System.Diagnostics.Process.Start()
   v System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   v Squirrel.UpdateManager.ApplyReleasesImpl.<>c.<invokePostInstall>b__10_6(ProcessStartInfo info)
   v Squirrel.EnumerableExtensions.ForEach[TSource](IEnumerable`1 source, Action`1 onNext)
   v Squirrel.UpdateManager.ApplyReleasesImpl.<invokePostInstall>d__10.MoveNext()
--- Konec trasování zásobníku z předchozího místa, ze kterého byla vyvolána výjimka ---
   v System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   v System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   v Squirrel.Utility.<LogIfThrows>d__42.MoveNext()
2019-11-11 16:41:55> Unhandled exception: System.AggregateException: Došlo k jedné nebo více chybám. ---> System.ComponentModel.Win32Exception: Zadaný spustitelný soubor není platnou aplikací pro tuto platformu OS.
   v System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   v System.Diagnostics.Process.Start()
   v System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   v Squirrel.UpdateManager.ApplyReleasesImpl.<>c.<invokePostInstall>b__10_6(ProcessStartInfo info)
   v Squirrel.EnumerableExtensions.ForEach[TSource](IEnumerable`1 source, Action`1 onNext)
   v Squirrel.UpdateManager.ApplyReleasesImpl.<invokePostInstall>d__10.MoveNext()
--- Konec trasování zásobníku z předchozího místa, ze kterého byla vyvolána výjimka ---
   v System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   v System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   v Squirrel.Utility.<LogIfThrows>d__42.MoveNext()
--- Konec trasování zásobníku z předchozího místa, ze kterého byla vyvolána výjimka ---
   v System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   v System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   v System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   v Squirrel.UpdateManager.ApplyReleasesImpl.<ApplyReleases>d__2.MoveNext()
--- Konec trasování zásobníku z předchozího místa, ze kterého byla vyvolána výjimka ---
   v System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   v System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   v Squirrel.UpdateManager.<FullInstall>d__10.MoveNext()
--- Konec trasování zásobníku z předchozího místa, ze kterého byla vyvolána výjimka ---
   v System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   v System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   v System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   v Squirrel.Update.Program.<Install>d__4.MoveNext()
   --- Konec trasování zásobníku pro vnitřní výjimku ---
   v System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   v System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   v System.Threading.Tasks.Task.Wait()
   v Squirrel.Update.Program.executeCommandLine(String[] args)
   v Squirrel.Update.Program.main(String[] args)
---> (Inner Exception #0) System.ComponentModel.Win32Exception (0x80004005): Zadaný spustitelný soubor není platnou aplikací pro tuto platformu OS.
   v System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   v System.Diagnostics.Process.Start()
   v System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   v Squirrel.UpdateManager.ApplyReleasesImpl.<>c.<invokePostInstall>b__10_6(ProcessStartInfo info)
   v Squirrel.EnumerableExtensions.ForEach[TSource](IEnumerable`1 source, Action`1 onNext)
   v Squirrel.UpdateManager.ApplyReleasesImpl.<invokePostInstall>d__10.MoveNext()
--- Konec trasování zásobníku z předchozího místa, ze kterého byla vyvolána výjimka ---
   v System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   v System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   v Squirrel.Utility.<LogIfThrows>d__42.MoveNext()
--- Konec trasování zásobníku z předchozího místa, ze kterého byla vyvolána výjimka ---
   v System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   v System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   v System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   v Squirrel.UpdateManager.ApplyReleasesImpl.<ApplyReleases>d__2.MoveNext()
--- Konec trasování zásobníku z předchozího místa, ze kterého byla vyvolána výjimka ---
   v System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   v System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   v Squirrel.UpdateManager.<FullInstall>d__10.MoveNext()
--- Konec trasování zásobníku z předchozího místa, ze kterého byla vyvolána výjimka ---
   v System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   v System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   v System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   v Squirrel.Update.Program.<Install>d__4.MoveNext()<---

2019-11-11 16:46:06> Program: Starting Squirrel Updater: --install .
2019-11-11 16:46:06> Program: Starting install, writing to C:\Users\tomas\AppData\Local\SquirrelTemp
2019-11-11 16:46:06> Program: About to install to: C:\Users\tomas\AppData\Local\electron_pdf
2019-11-11 16:46:06> Program: Install path C:\Users\tomas\AppData\Local\electron_pdf already exists, burning it to the ground
2019-11-11 16:46:10> CheckForUpdateImpl: Couldn't write out staging user ID, this user probably shouldn't get beta anything: System.IO.DirectoryNotFoundException: Část cesty C:\Users\tomas\AppData\Local\electron_pdf\packages\.betaId nebyla nalezena.
   v System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   v System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   v System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   v System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   v System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   v System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   v System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
   v Squirrel.UpdateManager.CheckForUpdateImpl.getOrCreateStagedUserId()
2019-11-11 16:46:10> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Část cesty C:\Users\tomas\AppData\Local\electron_pdf\packages\RELEASES nebyla nalezena.
   v System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   v System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   v System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   v Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   v Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
2019-11-11 16:46:10> CheckForUpdateImpl: Reading RELEASES file from C:\Users\tomas\AppData\Local\SquirrelTemp
2019-11-11 16:46:10> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2019-11-11 16:46:13> ApplyReleasesImpl: Writing files to app directory: C:\Users\tomas\AppData\Local\electron_pdf\app-0.0.1
2019-11-11 16:46:26> LogHost: Rigging execution stub for electron_pdf_ExecutionStub.exe to C:\Users\tomas\AppData\Local\electron_pdf\electron_pdf.exe
2019-11-11 16:46:36> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\tomas\AppData\Local\electron_pdf\app-0.0.1\electron_pdf.exe]
2019-11-11 16:46:36> ApplyReleasesImpl: Couldn't run Squirrel hook, continuing: C:\Users\tomas\AppData\Local\electron_pdf\app-0.0.1\electron_pdf.exe: System.ComponentModel.Win32Exception (0x80004005): Zadaný spustitelný soubor není platnou aplikací pro tuto platformu OS.
   v System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   v System.Diagnostics.Process.Start()
   v System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   v Squirrel.Utility.<InvokeProcessAsync>d__11.MoveNext()
--- Konec trasování zásobníku z předchozího místa, ze kterého byla vyvolána výjimka ---
   v System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   v System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   v Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass10_0.<<invokePostInstall>b__0>d.MoveNext()
2019-11-11 16:46:36> IEnableLogger: Failed to invoke post-install: System.ComponentModel.Win32Exception (0x80004005): Zadaný spustitelný soubor není platnou aplikací pro tuto platformu OS.
   v System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   v System.Diagnostics.Process.Start()
   v System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   v Squirrel.UpdateManager.ApplyReleasesImpl.<>c.<invokePostInstall>b__10_6(ProcessStartInfo info)
   v Squirrel.EnumerableExtensions.ForEach[TSource](IEnumerable`1 source, Action`1 onNext)
   v Squirrel.UpdateManager.ApplyReleasesImpl.<invokePostInstall>d__10.MoveNext()
--- Konec trasování zásobníku z předchozího místa, ze kterého byla vyvolána výjimka ---
   v System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   v System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   v Squirrel.Utility.<LogIfThrows>d__42.MoveNext()
2019-11-11 16:46:36> Unhandled exception: System.AggregateException: Došlo k jedné nebo více chybám. ---> System.ComponentModel.Win32Exception: Zadaný spustitelný soubor není platnou aplikací pro tuto platformu OS.
   v System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   v System.Diagnostics.Process.Start()
   v System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   v Squirrel.UpdateManager.ApplyReleasesImpl.<>c.<invokePostInstall>b__10_6(ProcessStartInfo info)
   v Squirrel.EnumerableExtensions.ForEach[TSource](IEnumerable`1 source, Action`1 onNext)
   v Squirrel.UpdateManager.ApplyReleasesImpl.<invokePostInstall>d__10.MoveNext()
--- Konec trasování zásobníku z předchozího místa, ze kterého byla vyvolána výjimka ---
   v System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   v System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   v Squirrel.Utility.<LogIfThrows>d__42.MoveNext()
--- Konec trasování zásobníku z předchozího místa, ze kterého byla vyvolána výjimka ---
   v System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   v System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   v System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   v Squirrel.UpdateManager.ApplyReleasesImpl.<ApplyReleases>d__2.MoveNext()
--- Konec trasování zásobníku z předchozího místa, ze kterého byla vyvolána výjimka ---
   v System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   v System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   v Squirrel.UpdateManager.<FullInstall>d__10.MoveNext()
--- Konec trasování zásobníku z předchozího místa, ze kterého byla vyvolána výjimka ---
   v System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   v System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   v System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   v Squirrel.Update.Program.<Install>d__4.MoveNext()
   --- Konec trasování zásobníku pro vnitřní výjimku ---
   v System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   v System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   v System.Threading.Tasks.Task.Wait()
   v Squirrel.Update.Program.executeCommandLine(String[] args)
   v Squirrel.Update.Program.main(String[] args)
---> (Inner Exception #0) System.ComponentModel.Win32Exception (0x80004005): Zadaný spustitelný soubor není platnou aplikací pro tuto platformu OS.
   v System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   v System.Diagnostics.Process.Start()
   v System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   v Squirrel.UpdateManager.ApplyReleasesImpl.<>c.<invokePostInstall>b__10_6(ProcessStartInfo info)
   v Squirrel.EnumerableExtensions.ForEach[TSource](IEnumerable`1 source, Action`1 onNext)
   v Squirrel.UpdateManager.ApplyReleasesImpl.<invokePostInstall>d__10.MoveNext()
--- Konec trasování zásobníku z předchozího místa, ze kterého byla vyvolána výjimka ---
   v System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   v System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   v Squirrel.Utility.<LogIfThrows>d__42.MoveNext()
--- Konec trasování zásobníku z předchozího místa, ze kterého byla vyvolána výjimka ---
   v System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   v System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   v System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   v Squirrel.UpdateManager.ApplyReleasesImpl.<ApplyReleases>d__2.MoveNext()
--- Konec trasování zásobníku z předchozího místa, ze kterého byla vyvolána výjimka ---
   v System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   v System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   v Squirrel.UpdateManager.<FullInstall>d__10.MoveNext()
--- Konec trasování zásobníku z předchozího místa, ze kterého byla vyvolána výjimka ---
   v System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   v System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   v System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   v Squirrel.Update.Program.<Install>d__4.MoveNext()<---

Thank you for making this great library.

**Comment by fcastilloec** [comment]
Sorry to point out the obvious but did you package the app using x32 architecture before using this module? You need to specify the architecture when using `electron-packager`. You'll also have to re-package the installer for both x32 and x64. If you really need compatibility with x32, you can pack only for x32 and use it on both x32 and x64 systems.
Some of your error messages are in another language and hoping that google translate did its job correctly, but it seems it's just a packaging issue.

**Comment by skopz356** [comment]
Yeah, now I realized it, my bad thanks a lot
