### ISSUE TITLE
MSI installer question

### ISSUE THREAD

**Issue by gpiroux** [electron-userland/electron-installer-windows#301]
First of all, thanks for the package, it is really useful :-)

I'm able to generate the windows installers (nupkg, exe, msi) with code signing certificate and everything seems to be OK. 

I'have just a question regarding the MSI package. When I launch the wizard, it doesn't display the name of the package but a series of digits as xxxxx.msi (see screenshot).

Is there a way to force the name of the package ?
Thanks

![Screenshot 2020-01-16 at 11 29 27](https://user-images.githubusercontent.com/2011650/72517511-d0846500-3853-11ea-9092-ea5b535deaed.png)

**Comment by fcastilloec** [comment]
I don't usually create a msi installer, just exe. From running the msi created from the example app for this tool, I don't get random digits but the name of the msi installer. I get the full path to the msi installer. Renaming the msi installer will also change what the dialog displays.
The biggest difference between what you do and the example is that we're not code signing (it's just an example) and you are. I'm not sure if this affects what the dialog shows.
You could try to modify the example so it can be code signed, this shouldn't be too hard, and test if you're experiencing the same random string, or what I saw.

Sorry, I couldn't duplicate this on my end.

**Comment by gpiroux** [comment]
Thanks @fcastilloec for your comment. 

Indeed, you are right, the app signature causes the issue.

![Screenshot 2020-01-20 at 09 38 12](https://user-images.githubusercontent.com/2011650/72711154-c79fd600-3b68-11ea-9f72-dccd5e212c08.png)

Any clue how to fix that ? I would be happy to contribute.

**Comment by fcastilloec** [comment]
I think what you need is to pass your own `options.signWithParams`.
The **string** in your config file should look like this:

`/a /f "path_to_certificate" /p "password" /d "description"`

The key part here is `"description"` which can contain spaces (I'm 90% sure about that). Try it and let me know if it works. If you can test with a description with and without spaces and report back, that'll be great!
Based on your tests, I might change the code so we always pass `/d` with the `productName` as the description.

**Comment by gpiroux** [comment]
Great !  That solves the issue :-)

![Screenshot 2020-01-21 at 12 18 21](https://user-images.githubusercontent.com/2011650/72800684-3738c280-3c48-11ea-9256-0f9afc71e520.png)

**Comment by gpiroux** [comment]
Is it possible to specify the icon with signTool ?

**Comment by fcastilloec** [comment]
Thanks so much for your tests! I will make sure that  `/d "description"` is always set to the `options.productName` on the next version of this module.

Regarding the icon, please open a new issue for that. It'll be easier to track it independently from the main issue in this thread. I can give you some ideas on how to fix it once you're created the other issue.
