### ISSUE TITLE
Installer creation fails on "Error NU5019"

### ISSUE THREAD

**Issue by grillem** [electron-userland/electron-installer-windows#316]
**What version of `electron-installer-windows` are you using?**
3.0.0
**What version of `node` and `npm` are you using?**
10.16.2
**What operating system are you using?**
W10
**Can you compile the [example app](https://github.com/electron-userland/electron-installer-windows/tree/master/example) successfully?**
Yes
**If not, paste here the output of the following commands:**

**What did you do? Please include the configuration you are using for `electron-installer-windows`.**
This is my package.json

{
  "name": "helloworld",
  "version": "1.0.0",
  "description": "An awesome app!",
  "main": "index.js",
  "author": {
    "name": "Guillem Magdaleno"
  },
  "scripts": {
    "dev": "electron index.js",
    "build": "electron-packager . app --platform win32 --arch x64 --out dist/",
    "setup": "electron-installer-windows --src dist/app-win32-x64/ --dest dist/installers/"
  },
  "devDependencies": {
    "electron": "^8.2.1",
    "electron-installer-windows": "^3.0.0",
    "electron-packager": "^14.2.1",
    "electron-rebuild": "^1.10.1",
    "electron-reload": "^1.5.0"
  }
}

**What actually happened?**
When running the setup script after having run the build script succesfully I get the following error:
> helloworld@1.0.0 setup C:\Users\Guillem\Desktop\HelloWorld
> electron-installer-windows --src dist/app-win32-x64/ --dest dist/installers/

Creating package (this may take a while)
{ Error: Command failed with a non-zero return code (1):
C:\Users\Guillem\Desktop\HelloWorld\node_modules\electron-installer-windows\vendor\nuget\nuget.exe pack C:\Users\Guillem\AppData\Local\Temp\electron-installer-1580094vKxLb8BZQP\helloworld_1.0.0_undefined\nuget\helloworld.nuspec -BasePath C:\Users\Guillem\AppData\Local\Temp\electron-installer-1580094vKxLb8BZQP\helloworld_1.0.0_undefined\helloworld -OutputDirectory C:\Users\Guillem\AppData\Local\Temp\electron-installer-1580094vKxLb8BZQP\helloworld_1.0.0_undefined\nuget -NoDefaultExcludes  
Intentando compilar el paquete desde 'helloworld.nuspec'.

Error NU5019: File not found: 'helloworld.exe'.
    at ChildProcess.process.on (C:\Users\Guillem\Desktop\HelloWorld\node_modules\@malept\cross-spawn-promise\dist\src\index.js:84:24)
    at ChildProcess.emit (events.js:198:13)
    at ChildProcess.cp.emit (C:\Users\Guillem\Desktop\HelloWorld\node_modules\cross-spawn\lib\enoent.js:34:29)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
  cmd:
   'C:\\Users\\Guillem\\Desktop\\HelloWorld\\node_modules\\electron-installer-windows\\vendor\\nuget\\nuget.exe',
  args:
   [ 'pack',
     'C:\\Users\\Guillem\\AppData\\Local\\Temp\\electron-installer-1580094vKxLb8BZQP\\helloworld_1.0.0_undefined\\nuget\\helloworld.nuspec',
     '-BasePath',
     'C:\\Users\\Guillem\\AppData\\Local\\Temp\\electron-installer-1580094vKxLb8BZQP\\helloworld_1.0.0_undefined\\helloworld',
     '-OutputDirectory',
     'C:\\Users\\Guillem\\AppData\\Local\\Temp\\electron-installer-1580094vKxLb8BZQP\\helloworld_1.0.0_undefined\\nuget',  
     '-NoDefaultExcludes' ],
  stdout:
   'Intentando compilar el paquete desde \'helloworld.nuspec\'. \r\n',
  stderr: 'Error NU5019: File not found: \'helloworld.exe\'.\r\n',
  code: 1 } 'Error: Command failed with a non-zero return code (1):\nC:\\Users\\Guillem\\Desktop\\HelloWorld\\node_modules\\electron-installer-windows\\vendor\\nuget\\nuget.exe pack C:\\Users\\Guillem\\AppData\\Local\\Temp\\electron-installer-1580094vKxLb8BZQP\\helloworld_1.0.0_undefined\\nuget\\helloworld.nuspec -BasePath C:\\Users\\Guillem\\AppData\\Local\\Temp\\electron-installer-1580094vKxLb8BZQP\\helloworld_1.0.0_undefined\\helloworld -OutputDirectory C:\\Users\\Guillem\\AppData\\Local\\Temp\\electron-installer-1580094vKxLb8BZQP\\helloworld_1.0.0_undefined\\nuget -NoDefaultExcludes\nIntentando compilar 
el paquete desde \'helloworld.nuspec\'. \r\n\nError NU5019: File not found: \'helloworld.exe\'.\n    at ChildProcess.process.on (C:\\Users\\Guillem\\Desktop\\HelloWorld\\node_modules\\@malept\\cross-spawn-promise\\dist\\src\\index.js:84:24)\n    
at ChildProcess.emit (events.js:198:13)\n    at ChildProcess.cp.emit (C:\\Users\\Guillem\\Desktop\\HelloWorld\\node_modules\\cross-spawn\\lib\\enoent.js:34:29)\n    at maybeClose (internal/child_process.js:982:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! helloworld@1.0.0 setup: `electron-installer-windows --src dist/app-win32-x64/ --dest dist/installers/`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the helloworld@1.0.0 setup script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Guillem\AppData\Roaming\npm-cache\_logs\2020-04-07T21_54_33_517Z-debug.log
The terminal process terminated with exit code: 1

Terminal will be reused by tasks, press any key to close it.

**Comment by fcastilloec** [comment]
I suggest reading very carefully the documentation for both `electron-packager` and `electron-installer-windows`. You are clearly specifying a custom name, **`app`**, when packaging your project which also changes your executable name to `app`. You are not specifying this to `electron-installer-windows` with the [options.exe](https://github.com/electron-userland/electron-installer-windows#optionsexe).
