### ISSUE TITLE
Invalid JSON config file

### ISSUE THREAD

**Issue by 1025ag** [electron-userland/electron-installer-windows#324]
Hello. I´m trying to add a windows installer to my electron application, but when I execute the corresponding command the console throws me this error:  Invalid JSON config file: config.json.

The application was built using angular. Here is My package.json:
{
  "name": "consultorio-ayacucho-app",
  "version": "0.0.0",
  "main": "main.js",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "electron": "electron .",
    "package": "electron-packager . consultorio-ayacucho-app --platform=win32 --arch=x64  --overwrite --asar=true --icon=./assets/icon.ico --prune=true --out=setup ",
    "setup":"electron-installer-windows  --src setup/consultorio-ayacucho-app-win32-x64  --config config.json"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~8.2.8",
    "@angular/cdk": "~8.2.3",
    "@angular/common": "~8.2.8",
    "@angular/compiler": "~8.2.8",
    "@angular/core": "~8.2.8",
    "@angular/fire": "^5.4.2",
    "@angular/forms": "~8.2.8",
    "@angular/material": "^8.2.3",
    "@angular/material-moment-adapter": "^9.0.0",
    "@angular/platform-browser": "~8.2.8",
    "@angular/platform-browser-dynamic": "~8.2.8",
    "@angular/router": "~8.2.8",
    "@fullcalendar/angular": "^4.4.2",
    "@fullcalendar/core": "^4.4.2",
    "@fullcalendar/daygrid": "^4.4.2",
    "@fullcalendar/timegrid": "^4.4.2",
    "@ngrx/effects": "^8.6.0",
    "@ngrx/store": "^8.6.0",
    "@ngrx/store-devtools": "^8.6.0",
    "chart.js": "^2.9.3",
    "firebase": "^7.15.1",
    "hammerjs": "^2.0.8",
    "install": "^0.13.0",
    "moment": "^2.24.0",
    "ng2-charts": "^2.3.0",
    "npm": "^6.14.5",
    "pdfmake": "^0.1.65",
    "pdfmake-wrapper": "^2.0.0",
    "rxjs": "~6.4.0",
    "sweetalert2": "^9.7.2",
    "tslib": "^1.10.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/architect": "^0.900.0-0 || ^0.900.0",
    "@angular-devkit/build-angular": "^0.803.24",
    "@angular/cli": "~8.3.6",
    "@angular/compiler-cli": "~8.2.8",
    "@angular/language-service": "~8.2.8",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "^5.0.0",
    "electron": "^9.0.5",
    "electron-installer-windows": "^3.0.0",
    "electron-packager": "^14.2.1",
    "firebase-tools": "^7.12.1",
    "fuzzy": "^0.1.3",
    "inquirer": "^6.2.2",
    "inquirer-autocomplete-prompt": "^1.0.1",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.5.3"
  }
}

Here is my config.json file: 
{
    "dest":"setup/",
    "iconUrl":"./assets/icon.ico",
    "icon":"./assets/icon.ico",
    "description":"Aplicación médica administrativa",
    "productName":"consultorioAyacuchoDemo",
    "name":"consultorioAyauchoDemoApp",
    "version":"1.0.0",
    "tags":[
        "Utility"
    ],
    "authors": ["Agustín La Valla"],
    "productDescription":"Aplicación médica administrativa"
}

  What should I do to fix this issue??

**Comment by fcastilloec** [comment]
The issues page of the project is to report bugs with the software and not a help page. Also, there's a reason why we have a template to report issues, following it makes it easier for us to figure out what's going on.
From what I can see, your config.json is a valid file. It does contain keys that aren't supported by this module. Please read the whole README file for the valid keys that can be used on the config file.
