### ISSUE TITLE
Does not work with electron 9

### ISSUE THREAD

**Issue by ThomasStubbe** [electron-userland/electron-installer-windows#325]
**What version of `electron-installer-windows` are you using?**
3.0.0

**What version of `node` and `npm` are you using?**
Node: v12.16.1
npm: 6.14.1

**What operating system are you using?**
Windows 10 Pro Version	10.0.18362 Build 18362

**Can you compile the [example app](https://github.com/electron-userland/electron-installer-windows/tree/master/example) successfully?**
It does work for electron 7.0.0, but when updating electron to 9.0.5, it does not:

**If not, paste here the output of the following commands:**

```
C:\Users\thoma\Downloads\electron-installer-windows-master\electron-installer-windows-master\example>npm run build

> example-electron-app@0.0.1 build C:\Users\thoma\Downloads\electron-installer-windows-master\electron-installer-windows-master\example
> npm run clean && npm run bundle:ia32 && npm run bundle:x64 && npm run exe:ia32 && npm run exe:x64


> example-electron-app@0.0.1 clean C:\Users\thoma\Downloads\electron-installer-windows-master\electron-installer-windows-master\example
> rimraf dist


> example-electron-app@0.0.1 bundle:ia32 C:\Users\thoma\Downloads\electron-installer-windows-master\electron-installer-windows-master\example
> electron-packager . --platform win32 --arch ia32 --out dist/ --icon resources/Icon.ico

Packaging app for platform win32 ia32 using electron v9.0.5
Wrote new app to dist\example-electron-app-win32-ia32

> example-electron-app@0.0.1 bundle:x64 C:\Users\thoma\Downloads\electron-installer-windows-master\electron-installer-windows-master\example
> electron-packager . --platform win32 --arch x64 --out dist/ --icon resources/Icon.ico

Packaging app for platform win32 x64 using electron v9.0.5
Wrote new app to dist\example-electron-app-win32-x64

> example-electron-app@0.0.1 exe:ia32 C:\Users\thoma\Downloads\electron-installer-windows-master\electron-installer-windows-master\example
> electron-installer-windows --src dist/example-electron-app-win32-ia32/ --dest dist/installers/ia32/ --config config.json

Creating package (this may take a while)
ExitCodeError: Command failed with a non-zero return code (1):
C:\Users\thoma\Downloads\electron-installer-windows-master\electron-installer-windows-master\example\node_modules\electron-installer-windows\vendor\nuget\nuget.exe pack C:\Users\thoma\AppData\Local\Temp\electron-installer-10800joaZzHVgEQ1k\example_electron_app_0.0.1_undefined\nuget\example_electron_app.nuspec -BasePath C:\Users\thoma\AppData\Local\Temp\electron-installer-10800joaZzHVgEQ1k\example_electron_app_0.0.1_undefined\example_electron_app -OutputDirectory C:\Users\thoma\AppData\Local\Temp\electron-installer-10800joaZzHVgEQ1k\example_electron_app_0.0.1_undefined\nuget -NoDefaultExcludes
Attempting to build package from 'example_electron_app.nuspec'.

The DateTimeOffset specified cannot be converted into a Zip file timestamp.
Parameter name: value
    at ChildProcess.<anonymous> (C:\Users\thoma\Downloads\electron-installer-windows-master\electron-installer-windows-master\example\node_modules\@malept\cross-spawn-promise\dist\src\index.js:84:24)
    at ChildProcess.emit (events.js:311:20)
    at ChildProcess.cp.emit (C:\Users\thoma\Downloads\electron-installer-windows-master\electron-installer-windows-master\example\node_modules\cross-spawn\lib\enoent.js:34:29)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5) {
  cmd: 'C:\\Users\\thoma\\Downloads\\electron-installer-windows-master\\electron-installer-windows-master\\example\\node_modules\\electron-installer-windows\\vendor\\nuget\\nuget.exe',
  args: [
    'pack',
    'C:\\Users\\thoma\\AppData\\Local\\Temp\\electron-installer-10800joaZzHVgEQ1k\\example_electron_app_0.0.1_undefined\\nuget\\example_electron_app.nuspec',
    '-BasePath',
    'C:\\Users\\thoma\\AppData\\Local\\Temp\\electron-installer-10800joaZzHVgEQ1k\\example_electron_app_0.0.1_undefined\\example_electron_app',
    '-OutputDirectory',
    'C:\\Users\\thoma\\AppData\\Local\\Temp\\electron-installer-10800joaZzHVgEQ1k\\example_electron_app_0.0.1_undefined\\nuget',
    '-NoDefaultExcludes'
  ],
  stdout: "Attempting to build package from 'example_electron_app.nuspec'.\r\n",
  stderr: 'The DateTimeOffset specified cannot be converted into a Zip file timestamp.\r\n' +
    'Parameter name: value\r\n',
  code: 1
} Error: Command failed with a non-zero return code (1):
C:\Users\thoma\Downloads\electron-installer-windows-master\electron-installer-windows-master\example\node_modules\electron-installer-windows\vendor\nuget\nuget.exe pack C:\Users\thoma\AppData\Local\Temp\electron-installer-10800joaZzHVgEQ1k\example_electron_app_0.0.1_undefined\nuget\example_electron_app.nuspec -BasePath C:\Users\thoma\AppData\Local\Temp\electron-installer-10800joaZzHVgEQ1k\example_electron_app_0.0.1_undefined\example_electron_app -OutputDirectory C:\Users\thoma\AppData\Local\Temp\electron-installer-10800joaZzHVgEQ1k\example_electron_app_0.0.1_undefined\nuget -NoDefaultExcludes
Attempting to build package from 'example_electron_app.nuspec'.

The DateTimeOffset specified cannot be converted into a Zip file timestamp.
Parameter name: value
    at ChildProcess.<anonymous> (C:\Users\thoma\Downloads\electron-installer-windows-master\electron-installer-windows-master\example\node_modules\@malept\cross-spawn-promise\dist\src\index.js:84:24)
    at ChildProcess.emit (events.js:311:20)
    at ChildProcess.cp.emit (C:\Users\thoma\Downloads\electron-installer-windows-master\electron-installer-windows-master\example\node_modules\cross-spawn\lib\enoent.js:34:29)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! example-electron-app@0.0.1 exe:ia32: `electron-installer-windows --src dist/example-electron-app-win32-ia32/ --dest dist/installers/ia32/ --config config.json`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the example-electron-app@0.0.1 exe:ia32 script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\thoma\AppData\Roaming\npm-cache\_logs\2020-06-25T08_16_45_244Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! example-electron-app@0.0.1 build: `npm run clean && npm run bundle:ia32 && npm run bundle:x64 && npm run exe:ia32 && npm run exe:x64`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the example-electron-app@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\thoma\AppData\Roaming\npm-cache\_logs\2020-06-25T08_16_45_341Z-debug.log
```

**What did you do? Please include the configuration you are using for `electron-installer-windows`.**
Default example code, except updating electron to 9.0.5:

```
"devDependencies": {
    "electron": "9.0.5",
    "electron-installer-windows": "*",
    "electron-packager": "^14.2.0",
    "rimraf": "^3.0.0"
  },
```

**What did you expect to happen?**
Installer created

**What actually happened?**
Package could not be created

**Comment by fcastilloec** [comment]
Your configuration file is jus the list of devDependencies and not a valid configuration file at all.
Please review all the README info, and check the [example app](https://github.com/electron-userland/electron-installer-windows/tree/master/example) to see how the configuration file looks like, and the options you can use there.

**Comment by ThomasStubbe** [comment]
As mentioned above, I changed nothing from the original package.json from the example except for one dependency: electron.
If you want the full package.json:

```
{
  "name": "example-electron-app",
  "description": "An example app, built with Electron.",
  "version": "0.0.1",
  "license": "MIT",
  "author": {
    "name": "Daniel Perez Alvarez",
    "email": "unindented@gmail.com",
    "url": "http://unindented.org/"
  },
  "private": true,
  "main": "src/index.js",
  "scripts": {
    "clean": "rimraf dist",
    "start": "electron .",
    "bundle:ia32": "electron-packager . --platform win32 --arch ia32 --out dist/ --icon resources/Icon.ico",
    "bundle:x64": "electron-packager . --platform win32 --arch x64 --out dist/ --icon resources/Icon.ico",
    "exe:ia32": "electron-installer-windows --src dist/example-electron-app-win32-ia32/ --dest dist/installers/ia32/ --config config.json",
    "exe:x64": "electron-installer-windows --src dist/example-electron-app-win32-x64/ --dest dist/installers/x64/ --config config.json",
    "build": "npm run clean && npm run bundle:ia32 && npm run bundle:x64 && npm run exe:ia32 && npm run exe:x64"
  },
  "devDependencies": {
    "electron": "9.0.6",
    "electron-installer-windows": "*",
    "electron-packager": "^14.2.0",
    "rimraf": "^3.0.0"
  },
  "dependencies": {
    "fs-plus": "^3.1.1",
    "yargs": "^15.1.0"
  }
}
```

**Comment by fcastilloec** [comment]
I'm sorry but I just tested this on Windows, Linux, and macOS and it works on all of them. As you did, I only changed the electron dependencies, and I used the same as you v9.0.5.
Regarding Windows itself, I used Windows 10 version 2004 build 19041.329.
I'm sorry but this is not reproducible

**Comment by DM164** [comment]
I've got the same identical problem, this was working before.

`C:\Users\denis\Documents\GitHub\Forget-Me-Not>electron-installer-windows --src "release-builds/Forget Me Not-win32-ia32/" --dest release-builds/installers/
Creating package (this may take a while)
ExitCodeError: Command failed with a non-zero return code (1):
C:\Users\denis\AppData\Roaming\npm\node_modules\electron-installer-windows\vendor\nuget\nuget.exe pack C:\Users\denis\AppData\Local\Temp\electron-installer--5456-pckD4610cy7W\forget_me_not_1.0.0_undefined\nuget\forget_me_not.nuspec -BasePath C:\Users\denis\AppData\Local\Temp\electron-installer--5456-pckD4610cy7W\forget_me_not_1.0.0_undefined\forget_me_not -OutputDirectory C:\Users\denis\AppData\Local\Temp\electron-installer--5456-pckD4610cy7W\forget_me_not_1.0.0_undefined\nuget -NoDefaultExcludes
Attempting to build package from 'forget_me_not.nuspec'.

Error NU5019: File not found: 'forget-me-not.exe'.
    at ChildProcess.<anonymous> (C:\Users\denis\AppData\Roaming\npm\node_modules\electron-installer-windows\node_modules\@malept\cross-spawn-promise\dist\src\index.js:84:24)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.cp.emit (C:\Users\denis\AppData\Roaming\npm\node_modules\electron-installer-windows\node_modules\cross-spawn\lib\enoent.js:34:29)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5) {
  cmd: 'C:\\Users\\denis\\AppData\\Roaming\\npm\\node_modules\\electron-installer-windows\\vendor\\nuget\\nuget.exe',
  args: [
    'pack',
    'C:\\Users\\denis\\AppData\\Local\\Temp\\electron-installer--5456-pckD4610cy7W\\forget_me_not_1.0.0_undefined\\nuget\\forget_me_not.nuspec',
    '-BasePath',
    'C:\\Users\\denis\\AppData\\Local\\Temp\\electron-installer--5456-pckD4610cy7W\\forget_me_not_1.0.0_undefined\\forget_me_not',
    '-OutputDirectory',
    'C:\\Users\\denis\\AppData\\Local\\Temp\\electron-installer--5456-pckD4610cy7W\\forget_me_not_1.0.0_undefined\\nuget',
    '-NoDefaultExcludes'
  ],
  stdout: "Attempting to build package from 'forget_me_not.nuspec'.\r\n",
  stderr: "Error NU5019: File not found: 'forget-me-not.exe'.\r\n",
  code: 1
} Error: Command failed with a non-zero return code (1):
C:\Users\denis\AppData\Roaming\npm\node_modules\electron-installer-windows\vendor\nuget\nuget.exe pack C:\Users\denis\AppData\Local\Temp\electron-installer--5456-pckD4610cy7W\forget_me_not_1.0.0_undefined\nuget\forget_me_not.nuspec -BasePath C:\Users\denis\AppData\Local\Temp\electron-installer--5456-pckD4610cy7W\forget_me_not_1.0.0_undefined\forget_me_not -OutputDirectory C:\Users\denis\AppData\Local\Temp\electron-installer--5456-pckD4610cy7W\forget_me_not_1.0.0_undefined\nuget -NoDefaultExcludes
Attempting to build package from 'forget_me_not.nuspec'.

Error NU5019: File not found: 'forget-me-not.exe'.
    at ChildProcess.<anonymous> (C:\Users\denis\AppData\Roaming\npm\node_modules\electron-installer-windows\node_modules\@malept\cross-spawn-promise\dist\src\index.js:84:24)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.cp.emit (C:\Users\denis\AppData\Roaming\npm\node_modules\electron-installer-windows\node_modules\cross-spawn\lib\enoent.js:34:29)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)

C:\Users\denis\Documents\GitHub\Forget-Me-Not>electron-installer-windows --src "release-builds/Forget Me Not-win32-ia32/" --dest installers/win/ --options.exe "Forget Me Not.exe"
Creating package (this may take a while)
ExitCodeError: Command failed with a non-zero return code (1):
C:\Users\denis\AppData\Roaming\npm\node_modules\electron-installer-windows\vendor\nuget\nuget.exe pack C:\Users\denis\AppData\Local\Temp\electron-installer--3692-yVQx8FXYiJ3f\forget_me_not_1.0.0_undefined\nuget\forget_me_not.nuspec -BasePath C:\Users\denis\AppData\Local\Temp\electron-installer--3692-yVQx8FXYiJ3f\forget_me_not_1.0.0_undefined\forget_me_not -OutputDirectory C:\Users\denis\AppData\Local\Temp\electron-installer--3692-yVQx8FXYiJ3f\forget_me_not_1.0.0_undefined\nuget -NoDefaultExcludes
Attempting to build package from 'forget_me_not.nuspec'.

The DateTimeOffset specified cannot be converted into a Zip file timestamp.
Parameter name: value
    at ChildProcess.<anonymous> (C:\Users\denis\AppData\Roaming\npm\node_modules\electron-installer-windows\node_modules\@malept\cross-spawn-promise\dist\src\index.js:84:24)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.cp.emit (C:\Users\denis\AppData\Roaming\npm\node_modules\electron-installer-windows\node_modules\cross-spawn\lib\enoent.js:34:29)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5) {
  cmd: 'C:\\Users\\denis\\AppData\\Roaming\\npm\\node_modules\\electron-installer-windows\\vendor\\nuget\\nuget.exe',
  args: [
    'pack',
    'C:\\Users\\denis\\AppData\\Local\\Temp\\electron-installer--3692-yVQx8FXYiJ3f\\forget_me_not_1.0.0_undefined\\nuget\\forget_me_not.nuspec',
    '-BasePath',
    'C:\\Users\\denis\\AppData\\Local\\Temp\\electron-installer--3692-yVQx8FXYiJ3f\\forget_me_not_1.0.0_undefined\\forget_me_not',
    '-OutputDirectory',
    'C:\\Users\\denis\\AppData\\Local\\Temp\\electron-installer--3692-yVQx8FXYiJ3f\\forget_me_not_1.0.0_undefined\\nuget',
    '-NoDefaultExcludes'
  ],
  stdout: "Attempting to build package from 'forget_me_not.nuspec'.\r\n",
  stderr: 'The DateTimeOffset specified cannot be converted into a Zip file timestamp.\r\n' +
    'Parameter name: value\r\n',
  code: 1
} Error: Command failed with a non-zero return code (1):
C:\Users\denis\AppData\Roaming\npm\node_modules\electron-installer-windows\vendor\nuget\nuget.exe pack C:\Users\denis\AppData\Local\Temp\electron-installer--3692-yVQx8FXYiJ3f\forget_me_not_1.0.0_undefined\nuget\forget_me_not.nuspec -BasePath C:\Users\denis\AppData\Local\Temp\electron-installer--3692-yVQx8FXYiJ3f\forget_me_not_1.0.0_undefined\forget_me_not -OutputDirectory C:\Users\denis\AppData\Local\Temp\electron-installer--3692-yVQx8FXYiJ3f\forget_me_not_1.0.0_undefined\nuget -NoDefaultExcludes
Attempting to build package from 'forget_me_not.nuspec'.

The DateTimeOffset specified cannot be converted into a Zip file timestamp.
Parameter name: value
    at ChildProcess.<anonymous> (C:\Users\denis\AppData\Roaming\npm\node_modules\electron-installer-windows\node_modules\@malept\cross-spawn-promise\dist\src\index.js:84:24)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.cp.emit (C:\Users\denis\AppData\Roaming\npm\node_modules\electron-installer-windows\node_modules\cross-spawn\lib\enoent.js:34:29)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)`
This is what I got, it's pretty similar.

**Comment by ThomasStubbe** [comment]
Thanks for the effort, switched to electron-builder, since that's working fine for me :) I've seen the same error online for different applications using NuGet (caused by invalid creation/modify dates), so it could have something to do with NuGet. It is strange that everything is working up to electron 8. It only occurs when I use electron 9. This happens for my own project as for the example project.
