### ISSUE TITLE
Cannot run app after installation finished

### ISSUE THREAD

**Issue by x4080** [electron-userland/electron-installer-windows#331]
Hi, its working great before but I think after I upgraded to electron 10.1.3, after installation finished, the app is not running - just processing something, here's my devDep

```
  "devDependencies": {
    "electron": "^10.1.3",
    "electron-builder": "^22.7.0",
    "electron-installer-windows": "^3.0.0",
    "electron-packager": "^15.1.0"
  },

```

And the electron packager files is work as usual using :
```
electron-packager . app--platform win32 --arch x64 --out dist/ --icon=build/icon.ico --overwrite
```

Any clue ?

Thanks

**Comment by fcastilloec** [comment]
There's not enough info to see what's happening. Also, this is more likely I bug with your code and not this module.
This module is basically copying files to locations, so the error has to be with your application

**Comment by x4080** [comment]
@fcastilloec Thanks for replying, thats what I thought too, the strange thing is if I run the files directly generated from electron-packager which is in folder dist/app-win32-x64 it runs just fine
