### ISSUE TITLE
Unable to add content to a new open window

### ISSUE THREAD

**Issue by NiteenRC** [electron-userland/electron-installer-windows#351]
**What version of `electron-installer-windows` are you using?**
"electron": "^17.1.0"

**What version of `node` and `npm` are you using?**
Angular CLI: 11.0.7
Node: 14.17.0

**What operating system are you using?**
OS: win64

**Can you compile the [example app](https://github.com/electron-userland/electron-installer-windows/tree/master/example) successfully?**
Yes

**If not, paste here the output of the following commands:**

```
$ git clone https://github.com/electron-userland/electron-installer-windows.git
$ cd electron-installer-windows/example
$ DEBUG='electron-installer-windows' npm run build
```

**What did you do? Please include the configuration you are using for `electron-installer-windows`.**
Application launched and its working fine. I have tested all functionalities but only one issue that I have mentioned below.

**What did you expect to happen?**
I am expecting to open new window and its opening perfectly but contents are not adding into opened window, 
    private _printPdf1(response) {
        const url = `http://localhost:4200/#table`;
        const myWindow = window.open(url, "_blank", "width=800,height=600,left=250,right=150");
        myWindow['response'] = response;
    }

   Note: Same above code is working in angular9+ without any issue its contents are added in new window. 

**What actually happened?**
Not adding response data into new Window. so window is blank.
Note: response is a Json data.

**Comment by fcastilloec** [comment]
Sorry for the late reply. The issue you're seeing has nothing to do with this tool. We simply get all your (already) packaged files and bundle them into an installer. You should test your app before using this tool, and even before using `electron-packager` which is required to use this tool.

**Comment by NiteenRC** [comment]
As mentioned, code is working in angular application wihout fail but only failing to add contents to new window.

Note: Opening new window(its working).
