### ISSUE TITLE
Error NU5019: File not found: 'LICENSE'

### ISSUE THREAD

**Issue by yfyfyfyfyfyf** [electron-userland/electron-installer-windows#353]
**What version of `electron-installer-windows` are you using?**
3.0.0

**What version of `node` and `npm` are you using?**
node: v16.17.1
npm: 8.15.0

**What operating system are you using?**
Windows 11

**Can you compile the [example app](https://github.com/electron-userland/electron-installer-windows/tree/master/example) successfully?**
Yes, I have successfully created two installers for the example project

**If not, paste here the output of the following commands:**

```
$ git clone https://github.com/electron-userland/electron-installer-windows.git
$ cd electron-installer-windows/example
$ DEBUG='electron-installer-windows' npm run build
```

**What did you do? Please include the configuration you are using for `electron-installer-windows`.**
"exe:ia32": "electron-installer-windows --src release/build/win-ia32-unpacked/ --dest release/build/win-ia32-unpacked/ --config windows-config.json",
"exe:x64": "electron-installer-windows --src release/build/win-unpacked/ --dest release/build/win-unpacked/ --config windows-config.json",
"package:windows": "npm run exe:ia32 && npm run exe:x64"

**What did you expect to happen?**
I have both unpacked versions working: ia32 and x64 and wanted to use electorn-intaller-windows to create two installers.

**What actually happened?**
It failed with the following error code

C:\Users\yanfu>cd C:\Users\yanfu\Downloads\video-experiments-app-windows && npm run package:windows

> berry@0.0.221002 package:windows
> npm run exe:ia32 && npm run exe:x64

> berry@0.0.221002 exe:ia32
> electron-installer-windows --src release/build/win-ia32-unpacked/ --dest release/build/win-ia32-unpacked/ --config windows-config.json

Creating package (this may take a while)
ExitCodeError: Command failed with a non-zero return code (1):
C:\Users\yanfu\Downloads\video-experiments-app-windows\node_modules\electron-installer-windows\vendor\nuget\nuget.exe pack C:\Users\yanfu\AppData\Local\Temp\electron-installer--6264-oLMGltYuWDRF\berry_0.0.221002_undefined\nuget\berry.nuspec -BasePath C:\Users\yanfu\AppData\Local\Temp\electron-installer--6264-oLMGltYuWDRF\berry_0.0.221002_undefined\berry -OutputDirectory C:\Users\yanfu\AppData\Local\Temp\electron-installer--6264-oLMGltYuWDRF\berry_0.0.221002_undefined\nuget -NoDefaultExcludes
Attempting to build package from 'berry.nuspec'.

Error NU5019: File not found: 'LICENSE'.
    at ChildProcess.<anonymous> (C:\Users\yanfu\Downloads\video-experiments-app-windows\node_modules\@malept\cross-spawn-promise\dist\src\index.js:99:24)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess.cp.emit (C:\Users\yanfu\Downloads\video-experiments-app-windows\node_modules\cross-spawn\lib\enoent.js:34:29)
    at maybeClose (node:internal/child_process:1093:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5) {
  cmd: 'C:\\Users\\yanfu\\Downloads\\video-experiments-app-windows\\node_modules\\electron-installer-windows\\vendor\\nuget\\nuget.exe',
  args: [
    'pack',
    'C:\\Users\\yanfu\\AppData\\Local\\Temp\\electron-installer--6264-oLMGltYuWDRF\\berry_0.0.221002_undefined\\nuget\\berry.nuspec',
    '-BasePath',
    'C:\\Users\\yanfu\\AppData\\Local\\Temp\\electron-installer--6264-oLMGltYuWDRF\\berry_0.0.221002_undefined\\berry',
    '-OutputDirectory',
    'C:\\Users\\yanfu\\AppData\\Local\\Temp\\electron-installer--6264-oLMGltYuWDRF\\berry_0.0.221002_undefined\\nuget',
    '-NoDefaultExcludes'
  ],
  stdout: "Attempting to build package from 'berry.nuspec'.\r\n",
  stderr: "Error NU5019: File not found: 'LICENSE'.\r\n",
  code: 1
} Error: Command failed with a non-zero return code (1):
C:\Users\yanfu\Downloads\video-experiments-app-windows\node_modules\electron-installer-windows\vendor\nuget\nuget.exe pack C:\Users\yanfu\AppData\Local\Temp\electron-installer--6264-oLMGltYuWDRF\berry_0.0.221002_undefined\nuget\berry.nuspec -BasePath C:\Users\yanfu\AppData\Local\Temp\electron-installer--6264-oLMGltYuWDRF\berry_0.0.221002_undefined\berry -OutputDirectory C:\Users\yanfu\AppData\Local\Temp\electron-installer--6264-oLMGltYuWDRF\berry_0.0.221002_undefined\nuget -NoDefaultExcludes
Attempting to build package from 'berry.nuspec'.

Error NU5019: File not found: 'LICENSE'.
    at ChildProcess.<anonymous> (C:\Users\yanfu\Downloads\video-experiments-app-windows\node_modules\@malept\cross-spawn-promise\dist\src\index.js:99:24)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess.cp.emit (C:\Users\yanfu\Downloads\video-experiments-app-windows\node_modules\cross-spawn\lib\enoent.js:34:29)
    at maybeClose (node:internal/child_process:1093:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)

**Comment by fcastilloec** [comment]
Seems like you don't have a license file which is required to create a package

**Comment by yfyfyfyfyfyf** [comment]
That's the weird part - the LICENSE file has been there all along, but for some reason, it's not picked up.
Any clue on how I can get around this? Thank you! 🙏

<img width="808" alt="Screen Shot 2022-10-04 at 10 05 40" src="https://user-images.githubusercontent.com/38646663/193767422-075cb22c-9298-4586-a4c6-ae08c4da187d.png">
